import React,{useState,useRef,useEffect} from 'react';
import {apiProduct,csvHeader,magicSearch,matchPhotoFiles,parseInventoryCsv,scanPhoto,uploadImage,ygoSearch} from '../lib/intake.js';
export default function IntakePanel({token,products,onFill,onUpdated}){
 const [name,N]=useState(''),[set,S]=useState(''),[num,Q]=useState(''),[game,G]=useState('Magic: The Gathering');
 const [rows,R]=useState([]),[photos,P]=useState([]),[note,M]=useState(''),[error,E]=useState(''),[busy,B]=useState(false);
 const [barcode,U]=useState(''),[camera,C]=useState(false),video=useRef(null),stream=useRef(null),timer=useRef(null);
 function stop(){if(timer.current)clearInterval(timer.current);timer.current=null;if(stream.current)stream.current.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;C(false);}
 useEffect(()=>()=>{if(timer.current)clearInterval(timer.current);if(stream.current)stream.current.getTracks().forEach(t=>t.stop());},[]);
 async function run(fn){B(true);M('');E('');try{await fn();}catch(e){E(e.message||'Request failed.');}finally{B(false);}}
 async function lookup(kind){await run(async()=>{const p=kind==='magic'?await magicSearch(name,set,num):await ygoSearch(name);const prefix=kind==='magic'?'MTG-'+p.setCode+'-'+p.collectorNumber:'YGO-'+p.productName;onFill({...p,sku:prefix.replace(/[^A-Za-z0-9._:-]/g,'-').slice(0,80)});M('Card filled. Verify printing, price, condition and image rights.');});}
 async function loadCsv(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;await run(async()=>{if(f.size>1024*1024)throw Error('CSV must be under 1 MB.');const p=parseInventoryCsv(await f.text());R(p);M(p.length+' rows validated.');});}
 async function importCsv(){await run(async()=>{if(!window.confirm('Create the validated products in AWS?'))return;const existing=new Set(products.map(p=>p.sku.toLowerCase()));let count=0,skip=0,fail='';for(const p of rows){if(existing.has(p.sku.toLowerCase())){skip++;continue;}try{await apiProduct('/products',token,'POST',p);count++;}catch(e){fail='Stopped at '+p.sku+': '+e.message;break;}}R([]);await onUpdated();M(count+' created, '+skip+' skipped. '+(fail||'Import complete.'));});}
 async function autofill(){await run(async()=>{const arr=[...rows];let n=0;for(let i=0;i<arr.length&&n<50;i++){const p=arr[i];if(p.category==='Magic: The Gathering'&&p.setCode&&p.collectorNumber&&!p.imageUrl){try{const m=await magicSearch('',p.setCode,p.collectorNumber);arr[i]={...p,imageUrl:m.imageUrl};n++;}catch{}await new Promise(resolve=>setTimeout(resolve,120));}}R(arr);M(n+' image URLs matched. Review usage rights.');});}
 function photoSelect(e){const f=Array.from(e.target.files||[]);e.target.value='';if(f.length>100){E('Maximum 100 images per batch.');return;}const result=matchPhotoFiles(f,products);P(result.hits);M(result.hits.length+' images matched; '+result.rejected.length+' rejected. '+result.rejected.slice(0,3).join('; '));}
 async function photosSave(){await run(async()=>{if(!window.confirm('Upload images and update AWS product records?'))return;let saved=0,fail='';for(const {file,product} of photos){try{const imageUrl=await uploadImage(file,token);await apiProduct('/products/'+encodeURIComponent(product.sku),token,'PUT',{...product,imageUrl});saved++;}catch(e){fail='Stopped: '+e.message;break;}}P([]);await onUpdated();M(saved+' photos saved. '+fail);});}
 async function photoScan(e){const f=e.target.files?.[0];e.target.value='';if(!f)return;await run(async()=>{const data=await scanPhoto(f,game,token),p=data.product||data.match;if(!p?.productName)throw Error('No verified match. Try manual search.');onFill({...p,category:game});M('Scan suggestion copied. Review before publishing.');});}
 async function cameraStart(){E('');try{if(!window.BarcodeDetector||!navigator.mediaDevices?.getUserMedia)throw Error('Browser camera scanning unavailable. Use manual barcode entry.');const formats=(await window.BarcodeDetector.getSupportedFormats()).filter(x=>['ean_13','ean_8','upc_a','upc_e','code_128'].includes(x));if(!formats.length)throw Error('No barcode formats available.');const d=new window.BarcodeDetector({formats});stream.current=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'}}});if(!video.current){stop();return;}video.current.srcObject=stream.current;await video.current.play();C(true);timer.current=setInterval(async()=>{try{if(!video.current||video.current.readyState<2)return;const hits=await d.detect(video.current);if(hits.length){U(hits[0].rawValue);onFill({barcode:hits[0].rawValue});M('Barcode copied.');stop();}}catch(e){E(e.message);stop();}},650);}catch(e){stop();E(e.message);}}
 function template(){const u=URL.createObjectURL(new Blob([csvHeader+'\n'],{type:'text/csv'}));const a=document.createElement('a');a.href=u;a.download='hobbyhub-import.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),500);}
 return <section className="intake-section"><h2>Scan, search and import cards</h2><p className="muted">Save hours on inventory intake. Always review recognition results before listing.</p>
 {note&&<p className="intake-success" role="status">{note}</p>}{error&&<p className="intake-error" role="alert">{error}</p>}
 <div className="intake-grid">
 <div className="intake-box"><h3>Card lookup</h3><label>Card name<input value={name} onChange={e=>N(e.target.value)} placeholder="Lightning Bolt"/></label><div className="intake-two"><label>Set<input value={set} onChange={e=>S(e.target.value)} placeholder="MH3"/></label><label>Collector #<input value={num} onChange={e=>Q(e.target.value)} placeholder="123"/></label></div><button disabled={busy||(!name.trim()&&!(set&&num))} onClick={()=>lookup('magic')}>Find Magic card</button><button disabled={busy||!name.trim()} className="secondary" onClick={()=>lookup('ygo')}>Find Yu-Gi-Oh!</button></div>
 <div className="intake-box"><h3>Photo recognition</h3><label>Game<select value={game} onChange={e=>G(e.target.value)}>{['Magic: The Gathering','Pokémon','Yu-Gi-Oh!'].map(g=><option key={g}>{g}</option>)}</select></label><label className="intake-upload">Identify a card from photo<input type="file" accept="image/jpeg,image/png" capture="environment" disabled={busy} onChange={photoScan}/></label><p className="muted">Requires private AWS scanning API; exact printing must be reviewed.</p></div>
 <div className="intake-box"><h3>Barcode scanner</h3><div className="intake-camera"><video ref={video} playsInline muted/>{!camera&&<span>Camera off</span>}</div><button className="secondary" type="button" onClick={camera?stop:cameraStart}>{camera?'Stop camera':'Start camera'}</button><label>Manual UPC / EAN<input value={barcode} onChange={e=>U(e.target.value)} inputMode="numeric"/></label><button disabled={!barcode.trim()} onClick={()=>{onFill({barcode:barcode.trim()});M('Barcode filled.');}}>Apply barcode</button></div>
 <div className="intake-box"><h3>Batch photos by SKU</h3><p>Name photos after an existing SKU, for example MTG-MH3-123.jpg. Up to 100 files.</p><label className="intake-upload">Select photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy} onChange={photoSelect}/></label>{photos.length>0&&<button disabled={busy} onClick={photosSave}>Attach {photos.length} images</button>}</div>
 </div><div className="intake-box intake-import"><h3>Import inventory from CSV</h3><button className="secondary" type="button" onClick={template}>Download CSV template</button><label className="intake-upload">Select CSV<input type="file" accept=".csv,text/csv" onChange={loadCsv} disabled={busy}/></label>{rows.length>0&&<><p>{rows.length} products ready. Preview:</p><div className="intake-scroll"><table><thead><tr><th>SKU</th><th>Product</th><th>Price</th><th>Stock</th></tr></thead><tbody>{rows.slice(0,6).map(p=><tr key={p.sku}><td>{p.sku}</td><td>{p.productName}</td><td>{'$'+Number(p.salePrice).toFixed(2)}</td><td>{p.quantityOnHand}</td></tr>)}</tbody></table></div><button disabled={busy} className="secondary" onClick={autofill}>Autofill Magic art</button><button disabled={busy} onClick={importCsv}>Import {rows.length} products</button></>}</div>
 </section>;
}
